apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: monitoring
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: access_key
      remoteRef:
        key: s3-credentials
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: s3-credentials
        property: secret_key
