apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: traefik
type: Opaque
stringData:
  email: gabidachaba@gmail.com
  apikey: MzU1ZjJjZDk1OGQ4NDFhMDVjMjIyY2JmNzI2ZGM3MzRhODM4Yw==
