rgname                 = "dev-pilotgab-rg"
service_principal_name = "dev-pilotgab-spn"
keyvault_name          = "dev-pilotgab-kv-101"
SUB_ID = ""
cluster_name = "dev-pilotgab-cluster"
node_pool_name = "devnp"
