application: traefik
clusterConfig:
  namespace: traefik
chart:
  name: traefik
  releaseName: traefik
  repoURL: https://traefik.github.io/charts
  targetRevision: v34.4.1
  values: |
    persistence:
      enabled: true
      name: ssl-certs
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: managed-csi
      path: /ssl-certs

    deployment:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 65532:65532 /ssl-certs && chmod -R 700 /ssl-certs"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /ssl-certs
              name: ssl-certs

      podSecurityContext:
        fsGroup: 65532
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        fsGroupChangePolicy: "Always"

    additionalArguments:
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=gabidachaba@gmail.com
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json

    deployment:
      additionalEnvs:
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-credentials
              key: apikey

    ingressClass:
      enabled: true
      isDefaultClass: true

    logs:
      general:
        level: "ERROR"

    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: 512Mi
  ```
