application: traefik
clusterConfig:
  namespace: traefik
chart:
  name: traefik
  releaseName: traefik
  repoURL: https://traefik.github.io/charts
  targetRevision: v34.4.1
  values: |
    additionalArguments:
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=gabidachaba@gmail.com
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json

    deployment:
      additionalEnvs:
        - name: CLOUDFLARE_DNS_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-credentials
              key: dns_api_token

      podSecurityContext:
        fsGroup: 65532
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        fsGroupChangePolicy: "Always"

    logs:
      general:
        level: "DEBUG"

    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            tls:
              enabled: true
              certResolver: cloudflare

    persistence:
      enabled: true
      name: ssl-certs
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: managed-csi
      path: /ssl-certs

    ingressClass:
      enabled: true
      isDefaultClass: true

    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: 512Mi
