apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat:10.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: apps
  labels:
    name: tomcat-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: tomcat.gabapp.tech
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: tomcat-service
                port:
                  number: 80
