apiVersion: v1
kind: Pod
metadata:
  name: debug-ssl-certs
  namespace: traefik
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /ssl-certs
          name: ssl-certs
  volumes:
    - name: ssl-certs
      persistentVolumeClaim:
        claimName: traefik
  restartPolicy: Never
