apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.selector.app }}
      version: {{ .Values.deployment.selector.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.selector.app }}
        version: {{ .Values.deployment.selector.version }}
    spec:
      containers:
        - name: {{ .Values.deployment.selector.app }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.deployment.env.datasourceUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.deployment.env.datasourceUser }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.deployment.env.datasourcePassword }}
          resources:
            requests:
              memory: {{ .Values.deployment.resources.requests.memory }}
              cpu: {{ .Values.deployment.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.resources.limits.memory }}
              cpu: {{ .Values.deployment.resources.limits.cpu }}
