apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pvc
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
---
apiVersion: v1
kind: Pod
metadata:
  name: init-data
  namespace: traefik
spec:
  containers:
    - name: init
      image: busybox
      command:
        [
          "sh",
          "-c",
          "mkdir -p /data && chown -R 65532:65532 /data && chmod -R 700 /data",
        ]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: traefiki-pvc
  restartPolicy: Never
