apiVersion: batch/v1
kind: Job
metadata:
  name: traefik-init-pvc
  namespace: traefik
spec:
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: init
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /ssl-certs && chown -R 65532:65532 /ssl-certs && chmod -R 700 /ssl-certs",
            ]
          volumeMounts:
            - name: ssl-certs
              mountPath: /ssl-certs
      volumes:
        - name: ssl-certs
          persistentVolumeClaim:
            claimName: ssl-certs
