apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  serviceName: {{ .Values.mysql.service.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
              name: mysql
          resources:
            requests:
              memory: {{ .Values.mysql.resources.requests.memory }}
              cpu: {{ .Values.mysql.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mysql.resources.limits.memory }}
              cpu: {{ .Values.mysql.resources.limits.cpu }}
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-storage-mysql-0
