apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-addons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pilotgab/bankapp-blue-green-deployment.git
    targetRevision: main
    path: "Cluster/monitor/RBAC/bankapps"
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{namespace}}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
