apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-role-sa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pilotgab/blue-green-bankapp-deployment.git
    targetRevision: main
    path: prom-roles
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
