apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compactor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-compactor
  template:
    metadata:
      labels:
        app: thanos-compactor
    spec:
      containers:
        - name: thanos-compactor
          image: quay.io/thanos/thanos:v0.37.2
          args:
            - compact
            - --data-dir=/data
            - --objstore.config-file=/etc/thanos/thanos.yaml
          volumeMounts:
            - name: thanos-objstore-config
              mountPath: /etc/thanos
            - name: thanos-compactor-data
              mountPath: /data
          envFrom:
            - secretRef:
                name: s3-credentials
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "500m"
              memory: 512Mi
      volumes:
        - name: thanos-objstore-config
          configMap:
            name: thanos-objstore-config
        - name: thanos-compactor-data
          persistentVolumeClaim:
            claimName: thanos-compactor-pvc
