apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore-config
  namespace: monitoring
data:
  thanos.yaml: |-
    type: S3
    config:
      bucket: "thanos-metrices"
      endpoint: "s3.amazonaws.com"
      region: "us-east-1"
      insecure: false
      signature_version2: false
      sse_config:
        type: "SSE-S3"
      max_retries: 10
