namespace: apps
ingress:
  name: bank-app-ingress
  host: ubank.gabapp.tech
  serviceName: bankapp-service
  servicePort: 80
service:
  name: bankapp-service
  type: ClusterIP
  port: 80
  targetPort: 8080
  selector:
    app: bankapp
    version: green
deployment:
  name: bankapp-blue
  replicas: 1
  selector:
    app: bankapp
    version: green
  image:
    repository: javaapplicationacr.azurecr.io/java-app
    tag: "84e5c47"
  containerPort: 8080
  env:
    datasourceUrl: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    datasourceUser: root
    datasourcePassword: Test@123
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"
mysql:
  name: mysql
  image:
    repository: mysql
    tag: "8"
  rootPassword: "Test@123"
  database: "bankappdb"
  service:
    name: mysql-service
    port: 3306
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: managed-premium
