apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-compactor-pv
  namespace: monitoring
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-08e5d6ae6c61ec8aa
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-compactor-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: gp2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-ruler-pv
  namespace: monitoring
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-0ceb3d78dfa31dd72
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-ruler-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  volumeName: thanos-ruler-pv
  storageClassName: gp3
