apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compactor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-compactor
  template:
    metadata:
      labels:
        app: thanos-compactor
    spec:
      serviceAccountName: thanos-compactor
      containers:
        - name: thanos-compactor
          image: quay.io/thanos/thanos:v0.37.2
          args:
            - compact
            - --data-dir=/data
            - --objstore.config-file=/etc/thanos/config.yaml
          volumeMounts:
            - name: thanos-objstore-config
              mountPath: /etc/thanos
            - name: thanos-compactor-data
              mountPath: /data
      volumes:
        - name: thanos-objstore-config
          configMap:
            name: thanos-objstore-config
        - name: thanos-compactor-data
          persistentVolumeClaim:
            claimName: thanos-compactor-pvc
