apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore-config
  namespace: monitoring
data:
  config.yaml: |
    type: S3
    config:
      bucket: prometheus-bucket
      endpoint: s3.us-east-1.amazonaws.com
      insecure: false
