kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: monitoring-config-access
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-config-bindin
  namespace: monitoring
subjects:
  - kind: Group
    name: system:serviceaccounts:monitoring
    apiGroup: rbac.authorization.k8s.io
    namespace: monitoring
roleRef:
  kind: Role
  name: monitoring-config-access
  apiGroup: rbac.authorization.k8s.io
